library(shiny)
library(plyr)
library(dplyr)
library(httr)
library(jsonlite)
library(ggplot2)
library(plotly)
library(knitr)
library(scales)
library(gridExtra)
library(anytime)
library(DT)

source("./scripts/apikey.R")
source("app_ui.R")
source("app_server.R")
source("./scripts/apikey.R")
source("./scripts/graphChampion.R")
source("./scripts/graphTime.R")
source("./scripts/graphWinratePie.R")
source("./scripts/graphKDAPie.R")
source("./scripts/graphRolePie.R")
source("./scripts/summaryTable.R")
source("./scripts/get.R")

# Get initial data so app_ui can fill filter dropdown in table
source("app_initialData.R")

shinyApp(ui = ui, server = server)